---
- name: My Test playbook
  hosts: all
  become: true
  tasks:
  - name: Install package
    yum: 
      name: ['git', 'make', 'gcc', 'wget', 'telnet', 'mysql', 'tree', 'which', 'docker*']
      state: installed 
